export default {
  API_URL: process.env.NEXT_PUBLIC_API_URL,
  LOCAL_STORAGE_USER_KEY: process.env.NEXT_PUBLIC_LOCAL_STORAGE_USER_KEY,
  LOCAL_STORAGE_TOKENS_KEY: process.env.NEXT_PUBLIC_LOCAL_STORAGE_TOKENS_KEY,
};
